### ISSUE TITLE
Seeing autoloading notices in log

### ISSUE THREAD

**Issue by JustinSainton** [zao-web/zao-woocommerce-quickbooks-online-integration#7]
```
[22-Sep-2017 20:03:35 UTC] PHP Fatal error:  Uncaught Error: Class 'ComposerAutoloaderInitb9e541571d8745739a09bfc8499bf6e8' not found in /dom10096/wp-content/plugins/zao-woocommerce-quickbooks-online-integration/vendor/autoload.php:7
 

Stack trace:
 

#0 /dom10096/wp-content/plugins/zao-woocommerce-quickbooks-online-integration/includes/functions/core.php(59): require_once()
 

#1 /dom10096/wp-content/plugins/zao-woocommerce-quickbooks-online-integration/zao-woocommerce-quickbooks-online-integration.php(54): Zao\WC_QBO_Integration\setup()
 

#2 /wordpress-4.8.2/wp-settings.php(303): include_once('/dom10096/wp-co...')
 

#3 /dom10096/wp-config.php(62): require_once('/wordpress-4.8....')
 

#4 /dom10096/wp-load.php(37): require_once('/dom10096/wp-co...')
 

#5 /wordpress-4.8.2/wp-admin/admin-ajax.php(22): require_once('/dom10096/wp-lo...')
 

#6 {main}
 

  thrown in /dom10096/wp-content/plugins/zao-woocommerce-quickbooks-online-integration/vendor/autoload.php on line 7
```

**Comment by jtsternberg** [comment]
I _think_ with the last deployment, this should be good.
